name: Detekt

on:
  push:
    branches:
      - master  # Change this to your default branch

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: '17'

      - name: Build and Run Detekt
        run: |
          ./gradlew detekt
